### ISSUE TITLE
Create your card

### ISSUE THREAD

**Issue by ankur0904** [ankur0904/card#18]
How to create your own card? 
**Reference:** https://dev.to/ankur0904/merge-your-first-pull-request-prepare-for-the-hacktoberfest-2023-1bn2

**Comment by PranjalPatel14** [comment]
What does that mean?

**Comment by anxbt** [comment]
hey i liked your project, but the background looks really bland.We should  work something up to make the background  look more interesting/eye-catching.

**Comment by ankur0904** [comment]
@anxbt 
Thanks, created the issue #21
