### ISSUE TITLE
Update the README.md file so that the code block will on separate line.

### ISSUE THREAD

**Issue by ankur0904** [ankur0904/card#6]
Files: https://github.com/ankur0904/card/blob/main/README.md
References: https://dev.to/ankur0904/merge-your-first-pull-request-prepare-for-the-hacktoberfest-2023-1bn2

**Comment by Priyanshu-bit** [comment]
hi , @ankur0904 ,I want to contribute

**Comment by ankur0904** [comment]
@Priyanshu-bit Please go ahead.
